//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parcheador3DS.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Parcheador3DS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] _3dstools {
            get {
                object obj = ResourceManager.GetObject("_3dstools", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] ctrtool {
            get {
                object obj = ResourceManager.GetObject("ctrtool", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] exeFSEUR {
            get {
                object obj = ResourceManager.GetObject("exeFSEUR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] exeFSUSA {
            get {
                object obj = ResourceManager.GetObject("exeFSUSA", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a font_message.cvt
        ///font_system.cvt
        ///message_english.mes
        ///movie\ending.moflex
        ///movie\Opening.moflex
        ///movie\Title_movie.moflex
        ///naui\config_ui.pac
        ///naui\menu_ui.pac
        ///naui\PC_Monitor.pac
        ///naui\sc10_bg.pac
        ///naui\Search.pac
        ///naui\SearchConfirm.pac
        ///texture\title1.cvt
        ///texture\anim\BG\Text_10-01_00000.cvt
        ///texture\anim\BG\Text_10-01_00001.cvt
        ///texture\anim\BG\Text_10-01_00002.cvt
        ///texture\anim\BG\Text_10-01_00003.cvt
        ///texture\anim\BG\Text_10-01_00004.cvt
        ///texture\anim\BG\Text_10-01_00005.cvt
        ///texture\anim\BG\Text_ [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string lista {
            get {
                return ResourceManager.GetString("lista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] makerom {
            get {
                object obj = ResourceManager.GetObject("makerom", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ÿ_-éá-é|`åPOâPEàt`åtpå`àpà¶èTã0à@å@à@åVáöÿÿ:HåXOâ&lt; å BàTï á á        /// áÄë½èð)áÿ_½èÿ/á á á áð)á&apos;¨(ÿÿH-é°âÐMâåå0 ã0å·ëå0å1å0å0å1å0å0å( ã å0å&lt;âh å å0åA?â å ååþëå0åSã
        ///0å
        ///ê0å&lt;â å å0åA?â å å0å0â0å áÐKâ½èH-é°â ÐMâåå0 á0Kå0 ã0åëå0å1å0å0å1å0å0å¨ å å0å0â [å å0å&lt;â å å0åA?â å å0å0âl å å0å0â å [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string ntreur {
            get {
                return ResourceManager.GetString("ntreur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ÿ_-éá-é|`ŸåPOâPEàt`ŸåtpŸå`†àp‡à¶èTã0ƒà@“å@„à@ƒåVáöÿÿ:HŸåXOâ&lt; Ÿå BàTï á á        /// áÄë½èð)áÿ_½èÿ/á á á áð)á&apos;¨(€ÿÿH-é°âÐMâåå0 ã0å·ëå0å1“å0å0å1“å0å0å( ã ƒå0å&lt;ƒâh Ÿå ƒå0åA?ƒâ å ƒååþëå0åSã
        ///0å
        ///ê0å&lt;ƒâ å ƒå0åA?ƒâ å ƒå0å0ƒâ0“å áÐKâˆ½è€H-é°â ÐMâåå0 á0Kå0 ã0å„ëå0å1“å0å0å1“å0å0å¨ Ÿå ƒå0å0ƒâ [å ƒå0å&lt;ƒâŒ Ÿå ƒå0åA?ƒâ å ƒå0å0ƒâl Ÿå ƒå0å0ƒâ å [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string ntrusa {
            get {
                return ResourceManager.GetString("ntrusa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] romfs {
            get {
                object obj = ResourceManager.GetObject("romfs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] xdelta3 {
            get {
                object obj = ResourceManager.GetObject("xdelta3", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
